BOOK_COPY_STATUS_AVAILABLE = 0
BOOK_COPY_STATUS_UNAVAILABLE = 1
BOOK_COPY_STATUS_DEMAGED = 2
BOOK_COPY_STATUS_LOST = 3

ORDER_STATUS_REQUESTED = 0
ORDER_STATUS_ACCPETED = 1
ORDER_STATUS_DECLINED = 2
ORDER_STATUS_EXPIRED = 3
ORDER_STATUS_COMPLETED = 4

EMAIL_ADDRESS = "phenixbookvector@gmail.com"
EMAIL_PASSWORD = "bookvector666"
