BOOK_COPY_STATUS_AVAILABLE = 0
BOOK_COPY_STATUS_UNAVAILABLE = 1
BOOK_COPY_STATUS_DEMAGED = 2
BOOK_COPY_STATUS_LOST = 3

NOTE_AVAILABLE = "You can borrow the book"
NOTE_NOT_AVAILABLE = "The book is already loaned out"
NOTE_DAMAGE = "The book is damage"
NOTE_LOST = "The book is lost"

ORDER_STATUS_REQUESTED = 0
ORDER_STATUS_ACCPETED = 1
ORDER_STATUS_DECLINED = 2
ORDER_STATUS_EXPIRED = 3
ORDER_STATUS_COMPLETED = 4
